### ISSUE TITLE
This error is coming while installing URY POS and URY Mosaic

### ISSUE THREAD

**Issue by ansariashfaque** [ury-erp/ury#1]
I read the document written by you, followed all the steps, after that I installed URY POS and URY Mosaic, this error is coming, this error is coming only at the time of build, I searched on frappe forum but I did not find the solution Please  help me in this problem. I have attached screenshot below.

**ERROR.**
Running build command for ury_mosaic
$ cd URYMosaic && npm install && yarn build

up to date, audited 159 packages in 4s

28 packages are looking for funding
  run `npm fund` for details

5 vulnerabilities (4 moderate, 1 high)

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
warning package.json: "dependencies" has dependency "autoprefixer" with range "^10.4.15" that collides with a dependency in "devDependencies" of the same name with version "^10.4.16"
$ vite build --base=/assets/ury_mosaic/URYMosaic/ && yarn copy-html-entry
vite v4.4.9 building for production...
✓ 7 modules transformed.
✓ built in 1.41s
Could not resolve "../../../doppio/libs/resourceManager" from "src/main.js"
file: /home/ash/bench1/apps/ury_mosaic/URYMosaic/src/main.js
error during build:
RollupError: Could not resolve "../../../doppio/libs/resourceManager" from "src/main.js"
    at error (file:///home/ash/bench1/apps/ury_mosaic/URYMosaic/node_modules/rollup/dist/es/shared/node-entry.js:2287:30)
    at ModuleLoader.handleInvalidResolvedId (file:///home/ash/bench1/apps/ury_mosaic/URYMosaic/node_modules/rollup/dist/es/shared/node-entry.js:24855:24)
    at file:///home/ash/bench1/apps/ury_mosaic/URYMosaic/node_modules/rollup/dist/es/shared/node-entry.js:24817:26
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Command failed: yarn build
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at run_build_command_for_apps (/home/ash/bench1/apps/frappe/esbuild/esbuild.js:436:5)
    at /home/ash/bench1/apps/frappe/esbuild/esbuild.js:88:35
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 1338,
  stdout: null,
  stderr: null
}
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: Command failed: yarn build
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at run_build_command_for_apps (/home/ash/bench1/apps/frappe/esbuild/esbuild.js:436:5)
    at /home/ash/bench1/apps/frappe/esbuild/esbuild.js:88:35
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 1338,
  stdout: null,
  stderr: null
}

Node.js v21.1.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ash/bench1/apps/frappe/frappe/utils/bench_helper.py", line 109, in <module>
    main()
  File "/home/ash/bench1/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/ash/bench1/env/lib/python3.10/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/ash/bench1/env/lib/python3.10/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/ash/bench1/env/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ash/bench1/env/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ash/bench1/env/lib/python3.10/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ash/bench1/env/lib/python3.10/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ash/bench1/apps/frappe/frappe/commands/utils.py", line 86, in build
    bundle(mode, apps=apps, hard_link=hard_link, verbose=verbose, skip_frappe=skip_frappe)
  File "/home/ash/bench1/apps/frappe/frappe/build.py", line 256, in bundle
    frappe.commands.popen(command, cwd=frappe_app_path, env=get_node_env(), raise_err=True)
  File "/home/ash/bench1/apps/frappe/frappe/commands/__init__.py", line 98, in popen
    raise subprocess.CalledProcessError(return_, command)
subprocess.CalledProcessError: Command 'yarn run production --run-build-command' returned non-zero exit status 1.
ash@pc:~/bench1$

![image](https://github.com/ury-erp/ury/assets/157605222/61a9af40-9667-4eaf-b962-994a23a93f70)

![image](https://github.com/ury-erp/ury/assets/157605222/48e8ff3b-fb3f-4cb2-b3b8-69b335973eba)

Thank You.

**Comment by Sanjusha-tridz** [comment]
Hi,

The error will not affect the functionality of "URY POS" or "URY Mosaic" ,it is a result of dependencies of "Doppio".
To resolve this, you can try installing the "doppio" app in your Bench environment. Use the following command:

```

bench get-app https://github.com/NagariaHussain/doppio

```

Installing "doppio" may provide the necessary dependencies or configurations required for the successful build of the "ury_pos" app. After installing "doppio," attempt to install "URY POS" and "URY Mosaic" again using the command

```

bench get-app https://github.com/ury-erp/pos.git

```

```
bench get-app https://github.com/ury-erp/mosaic.git
```
