### ISSUE TITLE
Internal Server Error ERROR: [Errno 39] Directory not empty: '/home/erp/frappe-bench/apps/mosaic' -> '/home/erp/frappe-bench/apps/ury_mosaic'

### ISSUE THREAD

**Issue by Makbool1** [ury-erp/ury#2]
after installing  $bench get-app https://github.com/NagariaHussain/doppio and $ bench get-app ury_mosaic https://github.com/ury-erp/mosaic.git my server is not working.

error screenshot attached...
![error](https://github.com/ury-erp/ury/assets/89012082/1985b8cd-4709-4f6d-970d-230cd9365b69)

erp@ubuntu:~/frappe-bench$ bench --site anzir.possy.online clear-cache
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/erp/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 109, in <module>
    main()
  File "/home/erp/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/erp/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/erp/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/erp/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/erp/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/erp/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/erp/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/erp/frappe-bench/env/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/erp/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 29, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/erp/frappe-bench/apps/frappe/frappe/commands/utils.py", line 109, in clear_cache
    frappe.connect(site)
  File "/home/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 273, in connect
    init(site)
  File "/home/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 252, in init
    setup_module_map()
  File "/home/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1559, in setup_module_map
    for module in get_module_list(app):
  File "/home/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1399, in get_module_list
    return get_file_items(os.path.join(os.path.dirname(get_module(app_name).__file__), "modules.txt"))
  File "/home/erp/frappe-bench/apps/frappe/frappe/__init__.py", line 1348, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'mosaic'

could you guide me how to rectify this issue

**Comment by ajmaltridz** [comment]
can you share with me the steps you followed? Share more context

**Comment by Amirmansi** [comment]
only make bench get-app https://github.com/ury-erp/ury.git 
then show 

<img width="568" height="138" alt="Image" src="https://github.com/user-attachments/assets/f3ac90fa-2856-4844-aadf-aa8036ce315b" />

**Comment by Amirmansi** [comment]
can you give me all steps to install and make it work at all

**Comment by Amirmansi** [comment]
<img width="1375" height="781" alt="Image" src="https://github.com/user-attachments/assets/85788b26-961c-4546-bc4b-8b4696904371" />
also i get your backup but stell show this

**Comment by shzdb** [comment]
Please use the database dump mentioned in this [comment](https://github.com/ury-erp/ury/issues/12#issuecomment-3165182908). Feel free to reach out if you are facing any other issues. Thank you
